# version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - ./app:/go/src/app
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    command: go run main.go
    ports:
      - "8080:8080"
